"""
Simple tool to convert a docs/ folder (Markdown) into a single self-contained HTML snapshot.
Usage:
  python3 scripts/generate_single_html.py --docs docs --out single-docs.html

Requirements:
  pip install markdown pygments
Notes:
  - This is a snapshot tool (for sharing/archiving). It will not reproduce Docusaurus JS interactions.
  - Images are referenced by path (not inlined). You can copy the images folder alongside the HTML.
"""
import argparse
import os
import pathlib
import re
import markdown
from datetime import datetime

MD_EXTS = ('.md', '.mdx', '.markdown')

HTML_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<title>Docs Snapshot</title>
<style>
/* Minimal styling inspired by Hellish theme; tweak as needed */
body{{background:#0b0c0e;color:#e6eef8;font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",Roboto,Arial;line-height:1.6;margin:0;padding:28px;}}
.container{{max-width:1100px;margin:0 auto;padding:28px;background:linear-gradient(180deg,rgba(255,255,255,0.01),transparent);border-radius:12px;box-shadow:0 12px 36px rgba(0,0,0,0.6);}}
h1,h2,h3{{color:#fff;margin-top:1.1rem}}
pre{{background:#07102a;padding:12px;border-radius:8px;overflow:auto;color:#dbeafe}}
code{{background:rgba(255,255,255,0.02);padding:2px 6px;border-radius:6px;font-family:monospace}}
a{{color:#ff6b6b;text-decoration:none}}
blockquote{{border-left:3px solid #ff6b6b;padding:8px 12px;background:rgba(255,107,107,0.02);border-radius:8px}}
hr{{border:none;border-top:1px solid rgba(255,255,255,0.03);margin:24px 0}}
.meta{{font-size:0.9rem;color:#98a0a8;margin-bottom:8px}}
.footer{{font-size:0.85rem;color:#7d8792;margin-top:28px;text-align:center}}
</style>
</head>
<body>
  <div class="container">
    <header>
      <h1>Docs Snapshot</h1>
      <div class="meta">Generated: {generated_at}</div>
      <hr/>
    </header>

    {content}

    <footer class="footer">Snapshot generated by scripts/generate_single_html.py</footer>
  </div>
</body>
</html>
"""

def read_markdown_files(docs_dir):
    files = []
    for root, _, filenames in os.walk(docs_dir):
        for fn in sorted(filenames):
            if fn.lower().endswith(MD_EXTS):
                path = pathlib.Path(root) / fn
                files.append(path)
    return files

def strip_frontmatter(text):
    # remove YAML frontmatter at top if present
    return re.sub(r'^---\\n.*?\\n---\\n', '', text, flags=re.S)

def main():
    p = argparse.ArgumentParser()
    p.add_argument('--docs', default='docs', help='Docs directory')
    p.add_argument('--out', default='single-docs.html', help='Output HTML file')
    args = p.parse_args()

    docs_dir = pathlib.Path(args.docs)
    if not docs_dir.exists():
        print(f"Docs folder not found: {docs_dir}")
        return

    md = markdown.Markdown(extensions=['fenced_code', 'codehilite', 'tables', 'toc'])
    content_blocks = []
    files = read_markdown_files(docs_dir)
    for path in files:
        text = path.read_text(encoding='utf-8')
        text = strip_frontmatter(text)
        html = md.convert(text)
        # simple heading showing filename
        title = path.relative_to(docs_dir)
        content_blocks.append(f'<section id="{path.stem}"><h2>{title}</h2>{html}</section><hr/>')
        md.reset()

    out_html = HTML_TEMPLATE.format(generated_at=datetime.utcnow().isoformat() + 'Z', content='\\n'.join(content_blocks))
    out_path = pathlib.Path(args.out)
    out_path.write_text(out_html, encoding='utf-8')
    print(f"Wrote single-file snapshot to {out_path.resolve()}")

if __name__ == '__main__':
    main()
